CLASS LHC_ZZCLR_WASTE_TRACK_01CIT DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZzclrWasteTrack01cit
        RESULT result.
ENDCLASS.

CLASS LHC_ZZCLR_WASTE_TRACK_01CIT IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
